---
- name: "Loop example"
- hosts: scarface
  become: true
  tasks:
    - name: create a list of users
      user:
        name: "{{ item }}"
        state: present
        groups: wheel
      loop:
        - violet
        - graham
        - bethany
